service: aqts-capture-state-machine

provider:
  name: aws
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'TEST'}
  deploymentBucket:
    name: iow-cloud-applications
  stackTags:
    "wma:applicationId": "Aquarius TS Capture State Machine"
    "wma:contact": "Andrew Yan ayan@usgs.gov"
    "wma:environment": ${self:provider.stage}
    "wma:taggingVersion": 0.0.1
    "wma:costCenter": TBD
    "commitIdentifier": "${git:sha1}"

custom:
  accountNumber: ${ssm:/iow/aws/accountNumber}

stepFunctions:
  stateMachines:
    aqtsCaptureStateMachine:
      role: arn:aws:iam::${self:custom.accountNumber}:role/step-functions-service-access
      name: aqts-capture-state-machine-${self:provider.stage}
      definition:
        Comment: "State machine representing extract, transformation, and load from Aquarius"
        StartAt: stateBypass
        States:
          stateBypass:
            Type: Choice
            Default: captureInitialLoad
            Choices:
              - Variable: "$.resumeState"
                StringEquals: captureInitialLoad
                Next: captureInitialLoad
              - Variable: "$.resumeState"
                StringEquals: tsTypeRouterTask
                Next: tsTypeRouterTask
              - Variable: "$.resumeState"
                StringEquals: tsDescriptionList
                Next: tsDescriptionList
              - Variable: "$.resumeState"
                StringEquals: tsCorrectedData
                Next: tsCorrectedData
              - Variable: "$.resumeState"
                StringEquals: tsTransformMapper
                Next: tsTransformMapper
          captureInitialLoad:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-raw-load-${self:provider.stage}-iowCapture
            TimeoutSeconds: 120
            Retry:
              - ErrorEquals:
                - States.TaskFailed
                IntervalSeconds: 10
                MaxAttempts: 3
                BackoffRate: 2
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: tsTypeRouterTask
          tsTypeRouterTask:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-ts-type-router-${self:provider.stage}-determineRoute
            TimeoutSeconds: 60
            Retry:
              - ErrorEquals:
                - States.TaskFailed
                IntervalSeconds: 3
                MaxAttempts: 3
                BackoffRate: 2
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: tsTypeRouterChoice
          tsTypeRouterChoice:
            Type: Choice
            Choices:
              - Variable: "$.type"
                StringEquals: tsDescriptionList
                Next: tsDescriptionList
              - Variable: "$.type"
                StringEquals: tsCorrectedData
                Next: tsCorrectedData
            Default: defaultSuccess
          tsDescriptionList:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-ts-description-${self:provider.stage}-processTsDescription
            ResultPath: $.timeSeries
            TimeoutSeconds: 60
            Retry:
              - ErrorEquals:
                - States.TaskFailed
                IntervalSeconds: 3
                MaxAttempts: 3
                BackoffRate: 2
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: tsTransformMapper
          tsCorrectedData:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-ts-corrected-${self:provider.stage}-preProcess
            ResultPath: $.timeSeries
            TimeoutSeconds: 60
            Retry:
              - ErrorEquals:
                - States.TaskFailed
                IntervalSeconds: 3
                MaxAttempts: 3
                BackoffRate: 2
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: tsTransformMapper
          tsTransformMapper:
            Type: Map
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: defaultSuccess
            ItemsPath: $.timeSeries
            MaxConcurrency: 0
            Iterator:
              StartAt: tsDataTypeIdentifier
              States:
                tsDataTypeIdentifier:
                  Type: Pass
                  Next: tsDataTypeRouter
                tsDataTypeRouter:
                  Type: Choice
                  Choices:
                    - Variable: $.dataType
                      StringEquals: tsDailyValueStatisticalTransform
                      Next: tsDailyValueStatisticalTransform
                  Default: defaultMapSuccess
                tsDailyValueStatisticalTransform:
                  Type: Pass
                  Next: loadToObservationDb
                loadToObservationDb:
                  Type: Pass
                  End: true
                defaultMapSuccess:
                  Type: Succeed
          errorHandler:
            Type: Task
            Parameters:
              "executionArn.$": "$$.Execution.Id"
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-error-handler-${self:provider.stage}-aqtsErrorHandler
            TimeoutSeconds: 15
            Next: defaultFail
          defaultSuccess:
            Type: Succeed
          defaultFail:
            Type: Fail

plugins:
  - serverless-step-functions
  - serverless-plugin-git-variables
