service: aqts-capture-state-machine

provider:
  name: aws
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'TEST'}
  deploymentBucket:
    name: iow-cloud-applications
  stackTags:
    "wma:applicationId": "Aquarius TS Capture State Machine"
    "wma:contact": "Andrew Yan ayan@usgs.gov"
    "wma:environment": ${self:provider.stage}
    "wma:taggingVersion": 0.0.1
    "wma:costCenter": TBD
    "commitIdentifier": "${git:sha1}"

custom:
  accountNumber: ${ssm:/iow/aws/accountNumber}
  tier:
    TEST:
      parsed: TEST
      lower: test
    QA:
      parsed: QA
      lower: qa
    PROD-EXTERNAL:
      parsed: PRODDashEXTERNAL
      lower: prod-external

stepFunctions:
  stateMachines:
    aqtsCaptureStateMachine:
      type: EXPRESS
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - arn:aws:logs:${self:provider.region}:${self:custom.accountNumber}:log-group:step-functions-${self:custom.tier.${self:provider.stage}.lower}:*
      alarms:
        topics:
          alarm:
            Ref: snsTopic
        metrics:
          - executionsFailed
          - executionThrottled
        treatMissingData: missing
      role: arn:aws:iam::${self:custom.accountNumber}:role/step-functions-service-access
      name: aqts-capture-state-machine-${self:provider.stage}
      definition:
        Comment: "State machine representing extract, transformation, and load from Aquarius"
        StartAt: captureInitialLoad
        States:
          captureInitialLoad:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-raw-load-${self:provider.stage}-iowCapture
            TimeoutSeconds: 120
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: tsTypeRouterTask
          tsTypeRouterTask:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-ts-type-router-${self:provider.stage}-determineRoute
            TimeoutSeconds: 75
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: tsTypeRouterChoice
          tsTypeRouterChoice:
            Type: Choice
            Choices:
              - Variable: "$.type"
                StringEquals: tsDescriptionList
                Next: tsDescriptionList
              - Variable: "$.type"
                StringEquals: tsCorrectedData
                Next: tsCorrectedData
              - Variable: "$.type"
                StringEquals: fieldVisitData
                Next: tsFieldVisit
            Default: defaultSuccess
          tsDescriptionList:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-ts-description-${self:provider.stage}-processTsDescription
            ResultPath: $.timeSeries
            TimeoutSeconds: 75
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: defaultSuccess
          tsCorrectedData:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-ts-corrected-${self:provider.stage}-preProcess
            ResultPath: $.timeSeries
            TimeoutSeconds: 105
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: tsDataTypeIdentifier
          tsFieldVisit:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-ts-field-visit-${self:provider.stage}-preProcess
            ResultPath: $.fieldVisit
            TimeoutSeconds: 105
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: fieldVisitTransform
          fieldVisitTransform:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-field-visit-transform-${self:provider.stage}-transform
            Parameters:
              id.$: $.id
              type.$: $.type
            ResultPath: $.fieldVisit
            TimeoutSeconds: 105
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: errorHandler
            Next: loadDiscreteGW
          loadDiscreteGW:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-discrete-loader-${self:provider.stage}-loadDiscrete
            InputPath: $.fieldVisit
            ResultPath: $.loadDiscreteGW
            TimeoutSeconds: 75
            End: true
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: errorHandler
          tsDataTypeIdentifier:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-stattype-router-${self:provider.stage}-determineRoute
            Parameters:
              uniqueId.$: $.timesSeries.timeSeries.uniqueId
              type.$: $.type
            ResultPath: $.out
            TimeoutSeconds: 75
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: tsDataTypeRouter
          tsDataTypeRouter:
            Type: Choice
            Choices:
              - Variable: $.out.dataType
                StringEquals: tsDailyValueStatisticalTransform
                Next: tsDailyValueStatisticalTransform
            Default: defaultSuccess
          tsDailyValueStatisticalTransform:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-dvstat-transform-${self:provider.stage}-transform
            Parameters:
              uniqueId.$: $.uniqueId
              id.$: $.id
              type.$: $.type
              dataType.$: $.out.dataType
            ResultPath: $.transformResult
            TimeoutSeconds: 75
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
            Next: loadToObservationDb
          loadToObservationDb:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-ts-loader-${self:provider.stage}-loadTimeSeries
            ResultPath: $.loadTimeSeries
            TimeoutSeconds: 75
            End: true
            Catch:
              - ErrorEquals:
                - States.ALL
                Next: errorHandler
          errorHandler:
            Type: Task
            Parameters:
              "executionArn.$": "$$.Execution.Id"
              "startInput.$": "$$.Execution.Input"
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-error-handler-${self:provider.stage}-aqtsErrorHandler
            TimeoutSeconds: 60
            Next: defaultFail
          defaultSuccess:
            Type: Succeed
          defaultFail:
            Type: Fail

resources:
  Resources:
    snsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:service}-${self:provider.stage}-topic
        TopicName: ${self:service}-${self:provider.stage}-topic
    stateDurationAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${self:provider.stage}-duration-alarm
        AlarmDescription: Notify when duration exceeds a threshold
        Namespace: 'AWS/States'
        Dimensions:
          - Name: StateMachineArn
            Value:
              Ref: AqtsDashcaptureDashstateDashmachineDash${self:custom.tier.${self:provider.stage}.parsed}
        MetricName: ExecutionTime
        Statistic: Maximum
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Period: 60
        EvaluationPeriods: 1
        Threshold: 295000  # just under 5 minutes
        TreatMissingData: missing
        AlarmActions:
          - Ref: snsTopic

plugins:
  - serverless-step-functions
  - serverless-plugin-git-variables
