service: aqts-capture-state-machine

provider:
  name: aws
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'TEST'}
  deploymentBucket:
    name: iow-cloud-applications
  stackTags:
    "wma:applicationId": "Aquarius TS Capture State Machine"
    "wma:contact": "Andrew Yan ayan@usgs.gov"
    "wma:environment": ${self:provider.stage}
    "wma:taggingVersion": 0.0.1
    "wma:costCenter": TBD

custom:
  accountNumber: ${ssm:/iow/aws/accountNumber}

stepFunctions:
  stateMachines:
    aqtsCaptureStateMachine:
      role: arn:aws:iam::${self:custom.accountNumber}:role/step-functions-service-access
      name: aqts-capture-state-machine-${self:provider.stage}
      definition:
        Comment: "State machine representing extract, transformation, and load from Aquarius"
        StartAt: captureInitialLoad
        States:
          captureInitialLoad:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-retriever-capture-raw-load-${self:provider.stage}-iowRetrieverCapture
            TimeoutSeconds: 60
            Retry:
              - ErrorEquals:
                - States.TaskFailed
                IntervalSeconds: 3
                MaxAttempts: 3
                BackoffRate: 2
            Next: tsTypeRouterTask
          tsTypeRouterTask:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-ts-type-router-${self:provider.stage}-determineRoute
            TimeoutSeconds: 60
            Retry:
              - ErrorEquals:
                - States.TaskFailed
                IntervalSeconds: 3
                MaxAttempts: 3
                BackoffRate: 2
            Next: tsTypeRouterChoice
          tsTypeRouterChoice:
            Type: Choice
            Choices:
              - Variable: "$.type"
                StringEquals: tsDescription
                Next: tsDescription
            Default: defaultSuccess
          tsTypeRouterTask:
            Type: Task
            Resource: arn:aws:lambda:${self:provider.region}:${self:custom.accountNumber}:function:aqts-capture-ts-description-${self:provider.stage}-echoObject
            TimeoutSeconds: 60
            Retry:
              - ErrorEquals:
                - States.TaskFailed
                IntervalSeconds: 3
                MaxAttempts: 3
                BackoffRate: 2
            Next: defaultSuccess
          defaultSuccess:
            Type: Succeed

plugins:
  - serverless-step-functions
